language: ruby
rvm:
  - 2.1.3
  - ruby-head
script: bundle exec rspec
before_script: bundle exec rake db:setup
env:
  global:
    - secure: | # CODECLIMATE_REPO_TOKEN
        mUeD1q8rI0F+xeH5f7e6ey9mm+Nu7d8UVDP0q3SEdFhrLz2K3vFoZ7gyrQoS
        h1I0rldW1qAhXPWWXDpk+K0oFsXe9vzGupdmepS4HIBTUYsKD08b7KGE6dOo
        LOBwDLpfGbHhEjC2soeugD9mr8WwL/tDQIInm/aTxI64xE94FTk=
matrix:
  allow_failures:
    - rvm: ruby-head
branches:
  only:
    - master
